In [ ]:
import torch 
import torch.nn as nn
import torch.nn.functional as F
import numpy as np 
import PIL.Image as image
import pandas as pd
from sklearn.preprocessing import LabelEncoder

**We will treat different sides of the iris as different subjects , This is a check for the balance of the data classes , and we can see that the data is reasonably balanced**

In [53]:
import os
data_path = 'DataSet/CASIA-Iris-Thousand' 
folders = os.listdir(data_path)
total_classes = 0
image_counts = {}
for fold in folders:
    sub_path = os.path.join(data_path, fold)
    if os.path.isdir(sub_path):
        for side in ['L', 'R']:
            side_path = os.path.join(sub_path, side)
            if os.path.exists(side_path):
                total_classes += 1
                imgs = os.listdir(side_path)
                image_counts[side_path] = len(imgs)
print(f"Total Unique Irises (Classes): {total_classes}")
print(f"Average Images per Class: {sum(image_counts.values())/len(image_counts):.2f}")
print(f"Min images: {min(image_counts.values())}, Max images: {max(image_counts.values())}")

Total Unique Irises (Classes): 2000
Average Images per Class: 10.01
Min images: 10, Max images: 11

In [70]:
label_mapping=pd.read_csv(r"DataSet\iris_thousands.csv",index_col=0)

In [71]:
label_mapping

       Label                                          ImagePath
0      437-R  /kaggle/input/casia-iris-thousand/CASIA-Iris-T...
1      437-R  /kaggle/input/casia-iris-thousand/CASIA-Iris-T...
2      437-R  /kaggle/input/casia-iris-thousand/CASIA-Iris-T...
3      437-R  /kaggle/input/casia-iris-thousand/CASIA-Iris-T...
4      437-R  /kaggle/input/casia-iris-thousand/CASIA-Iris-T...
...      ...                                                ...
19995  715-L  /kaggle/input/casia-iris-thousand/CASIA-Iris-T...
19996  715-L  /kaggle/input/casia-iris-thousand/CASIA-Iris-T...
19997  715-L  /kaggle/input/casia-iris-thousand/CASIA-Iris-T...
19998  715-L  /kaggle/input/casia-iris-thousand/CASIA-Iris-T...
19999  715-L  /kaggle/input/casia-iris-thousand/CASIA-Iris-T...

[20000 rows x 2 columns]

**Now we need to label encode the classes to be able to use them in the model training**

In [ ]:
le = LabelEncoder()
label_mapping['encoded_label'] = le.fit_transform(label_mapping['Label'])

In [74]:
label_mapping

       Label                                          ImagePath  encoded_label
0      437-R  /kaggle/input/casia-iris-thousand/CASIA-Iris-T...            875
1      437-R  /kaggle/input/casia-iris-thousand/CASIA-Iris-T...            875
2      437-R  /kaggle/input/casia-iris-thousand/CASIA-Iris-T...            875
3      437-R  /kaggle/input/casia-iris-thousand/CASIA-Iris-T...            875
4      437-R  /kaggle/input/casia-iris-thousand/CASIA-Iris-T...            875
...      ...                                                ...            ...
19995  715-L  /kaggle/input/casia-iris-thousand/CASIA-Iris-T...           1430
19996  715-L  /kaggle/input/casia-iris-thousand/CASIA-Iris-T...           1430
19997  715-L  /kaggle/input/casia-iris-thousand/CASIA-Iris-T...           1430
19998  715-L  /kaggle/input/casia-iris-thousand/CASIA-Iris-T...           1430
19999  715-L  /kaggle/input/casia-iris-thousand/CASIA-Iris-T...           1430

[20000 rows x 3 columns]